variables:
  S3_BUCKET_NAME: "my-next-app"

build:
  image: node:14.16.0
  script:
    - yarn install --frozen-lockfile
    - yarn build


deploy:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
  - ls
  only:
  - main
